### ISSUE TITLE
Profile Page Previously incorrect answers buttons

### ISSUE THREAD

**Issue by clairevita** [clairevita/uguale#40]

**Comment by dmcc789** [comment]
Current status: On the /User page we have a card of buttons set up for previously incorrect answers.  The card renders a new button component called DashBttn that comes wrapped in the <link> element to= "/game".  

Still to do:  How to populate the numbers in the buttons.  How to automatically create a new button each time an answer is wrong.  How to pass the number from the button to be populated on load of /game page.
